### ISSUE TITLE
Gentona - WebFont

### ISSUE THREAD

**Issue by ewlarson** [jhu-sheridan-libraries/geoblacklight#14]
From https://dataservices.library.jhu.edu/
Via https://dataservices.library.jhu.edu/?sccss=1&ver=5.3.2

How is this font licensed? Can we use it within GBL?

**Comment by prairieskygal** [comment]
@ewlarson Good question about licensing, I don't actually know. We've been deploying it on our web properties across the board (including 3rd party products) because it's defined in the JHU brand identity, but there is no information about licensing for 3rd party products in the guidelines. They do indicate that the fallback font is Tahoma if Gentona can't be implemented for technical reasons.

If the styles I shared work, let's move forward with Gentona. If they don't work let's not spend a lot of time troubleshooting until I get confirmation about the licensing.

**Comment by ewlarson** [comment]
Added Gentona in https://github.com/jhu-sheridan-libraries/geoblacklight/pull/16/commits/b52f21cb7a0bb0ae32bc0b0c84a81eea90f0a590

Leaving this issue open in case we need to add licensing information to the project repo.

**Comment by ewlarson** [comment]
Closing. Completed during the [February Winter Code Sprint](https://github.com/jhu-sheridan-libraries/geoblacklight/projects/1).
